### global defaults ############################################################

rails_env: production
madek_git_ref: master
madek_root_dir: /home/madek/madek_app
mri_ruby_version: 2.1.2

zencoder_api_key_file: /etc/madek/zencoder_api_key.txt

# database
database:
  username: madek
  password: madek
  hostname: localhost
  port: 5432
  database: madek_production
  pool: 10

