- file:
    path: "{{madek_root_dir}}/webapp/node_modules"
    owner: "{{madek_user}}"
    group: "{{madek_user}}"
    state: directory
    recurse: yes

- name: npm install
  shell: su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh
          && rbenv-load
          && cd {{madek_root_dir}}/webapp/
          && npm install' {{madek_user}}
  register: npm_install


