- hosts: madek

  vars:

    rails_env: production
    madek_root_dir: /home/madek/madek_app
    madek_git_ref: 2.0.8
    mri_ruby_version: 2.1.2

    # database
    database:
      username: madek
      password: madek
      hostname: localhost
      port: 5432
      database: madek_production
      pool: 10


  roles: 
    - role: debuntu-setup
    - role: postgresql
    - role: madek-user

    - role: rbenv
      user: madek

    - role: rbenv-ruby 
      user: madek
      ruby: 
        version: "{{mri_ruby_version}}"
        alias: 2.1
        present: True
        default: True

    - role: apache-httpd
      apache_httpd_enabled_modules: 
        - expires
        - headers
        - proxy
        - proxy_http
        - rewrite
        - xsendfile

    - role: passenger 

    - role: madek

