
- hosts: all
  tasks: 
  - apt:  upgrade=dist
          update_cache=yes 
          cache_valid_time=3600


- hosts: madek

  roles: 
    - role: debuntu-setup
    - role: postgresql
    - role: ftp-server
    - role: madek-user

    - role: rbenv
      user: madek

    - role: rbenv-ruby 
      user: madek
      ruby: 
        version: "{{mri_ruby_version}}"
        alias: 2.1
        present: True
        default: True

    - role: apache-httpd

    - role: passenger 

    - role: madek

    - role: madek-dropbox

    - role: madek-zencoder
      tags: [zencoder]


