- hosts: madek

  vars:

  vars_files:
    - vars_madek.yml

  roles: 
    - role: debuntu-setup
    - role: postgresql
    - role: madek-user

    - role: rbenv
      user: madek

    - role: rbenv-ruby 
      user: madek
      ruby: 
        version: "{{mri_ruby_version}}"
        alias: 2.1
        present: True
        default: True

    - role: apache-httpd
      apache_httpd_enabled_modules: 
        - expires
        - headers
        - proxy
        - proxy_http
        - rewrite
        - xsendfile

    - role: passenger 

    - role: madek

