- template: >
    src=dump.sh
    dest=/etc/cron.daily/madek-db-backup-{{rails_env}}
    mode=0755
  when: db_dumps_enabled

- file: >
    path=/etc/cron.daily/madek-db-backup-{{rails_env}}
    state=absent 
  when: not db_dumps_enabled


