- name: Add the group "madek"
  group:  name=madek
          system=true

- name: Add the user "madek"
  user: name=madek
        generate_ssh_key=yes
        group=madek
        system=yes
        shell=/bin/bash
        uid=1002

- name: Create or update postgresql user
  postgresql_user:  name={{database.username}}
                    password={{database.password}}
                    role_attr_flags=CREATEDB,SUPERUSER
                    login_user=root
                    port={{database.port}}

