
- name: Create secrets
  template: src=secrets.yml
            dest={{madek_webapp_dir}}/config/secrets.yml
            owner={{madek_user}}
            group={{madek_user}}
            mode=0600
  register: secret


- name: Precompile assets
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh
            && rbenv-load
            && cd {{madek_webapp_dir}}
            && export RAILS_ENV={{rails_env}}
            && export RBENV_VERSION={{rubies.mri.version}}
            && rm -rf public/assets/*
            && rm -rf tmp/cache/*
            && bundle exec rake assets:precompile' {{madek_user}}
          executable=/bin/bash
  register: precompile_assets
  changed_when: not precompile_assets.stderr | match("")


