### specific settings for a local virtual machine 

madek_git_ref: ts


release: 
  version_major: 10
  version_minor: 2
  version_patch: 0
  version_pre: ¡DELETE!
  version_build: ¡DELETE!

color_scheme: blue
custom_color: '#6149c1' # purple

### Zencoder ##################################################################

zencoder_enabled: False
zencoder_test_mode: True


### Zhdk ######################################################################

zhdk_integration: False



### Passenger #################################################################
passenger_min_instances: 1


